path:
  tokens:   tokens/**/*.yml
  assets:   assets
  dist:     dist
  fonts:    ../fonts
  html:     index.html
  json:
    tokens: dist/json
  scss:
    tokens: dist/scss/tokens
    src:    dist/scss/**/*.scss
    dest:   dist/css

formats:
          - json
          - scss
